# Generated by Django 4.2.3 on 2023-07-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_ticket_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='author',
        ),
    ]
