# Generated by Django 4.2.3 on 2023-08-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_review_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
