# Generated by Django 4.2.3 on 2023-08-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_review_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='average',
        ),
    ]
