# Generated by Django 4.2.3 on 2023-08-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_remove_review_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average',
            field=models.JSONField(default={'key': 0}),
            preserve_default=False,
        ),
    ]
