# Generated by Django 4.2.3 on 2023-08-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_alter_review_average'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='time_created',
            new_name='date_created',
        ),
    ]
