# Generated by Django 4.2.3 on 2023-08-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_remove_review_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
