# Generated by Django 4.2.3 on 2023-08-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_review_average'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='average',
            new_name='hearts',
        ),
    ]
