# Generated by Django 4.2.3 on 2023-08-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_rename_average_review_hearts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, max_length=8192),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=2048, verbose_name='description'),
        ),
    ]
